# Generated by Django 6.0.1 on 2026-03-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='source_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_pins', to='pins.pinrequest'),
        ),
        migrations.AddField(
            model_name='pinrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
