# Generated by Codex on 2026-03-13

from django.db import migrations


def sync_legacy_schema(apps, schema_editor):
    connection = schema_editor.connection
    introspection = connection.introspection
    existing_tables = set(introspection.table_names())

    AccountUser = apps.get_model("accounts", "User")
    Pin = apps.get_model("pins", "Pin")
    PinRequest = apps.get_model("pins", "PinRequest")
    Wallet = apps.get_model("wallets", "Wallet")
    LedgerEntry = apps.get_model("wallets", "LedgerEntry")
    Withdrawal = apps.get_model("withdrawals", "Withdrawal")
    AutoWithdrawalLog = apps.get_model("withdrawals", "AutoWithdrawalLog")
    RewardTier = apps.get_model("rewards", "RewardTier")
    UserReward = apps.get_model("rewards", "UserReward")
    SalaryLog = apps.get_model("rewards", "SalaryLog")
    ComplaintFeedback = apps.get_model("complaints", "ComplaintFeedback")
    BinaryNode = apps.get_model("network", "BinaryNode")

    def table_columns(table_name):
        with connection.cursor() as cursor:
            return {
                column.name
                for column in introspection.get_table_description(cursor, table_name)
            }

    def rename_column(table_name, old_name, new_name):
        if table_name not in existing_tables:
            return
        columns = table_columns(table_name)
        if old_name in columns and new_name not in columns:
            schema_editor.execute(
                f'ALTER TABLE "{table_name}" RENAME COLUMN "{old_name}" TO "{new_name}"'
            )

    def add_column(table_name, column_name, sql_type, default_sql=None, not_null=True):
        if table_name not in existing_tables:
            return
        columns = table_columns(table_name)
        if column_name in columns:
            return
        default_clause = f" DEFAULT {default_sql}" if default_sql is not None else ""
        null_clause = " NOT NULL" if not_null else ""
        schema_editor.execute(
            f'ALTER TABLE "{table_name}" ADD COLUMN "{column_name}" {sql_type}{default_clause}{null_clause}'
        )

    missing_models = [
        (Wallet, "wallets_wallet"),
        (LedgerEntry, "wallets_ledgerentry"),
        (AutoWithdrawalLog, "withdrawals_autowithdrawallog"),
        (UserReward, "rewards_userreward"),
        (SalaryLog, "rewards_salarylog"),
        (ComplaintFeedback, "complaints_complaintfeedback"),
        (BinaryNode, "network_binarynode"),
    ]
    for model, table_name in missing_models:
        if table_name not in existing_tables:
            schema_editor.create_model(model)
            existing_tables.add(table_name)

    rename_column("accounts_user", "left_count", "left_team_count")
    rename_column("accounts_user", "right_count", "right_team_count")
    rename_column("accounts_user", "current_income_pkr", "current_income")
    rename_column("accounts_user", "reward_income_pkr", "reward_income")
    rename_column("accounts_user", "total_withdrawn_pkr", "total_withdrawn")
    rename_column("accounts_user", "avatar", "profile_picture")
    add_column("accounts_user", "payment_method", "varchar(20)", "'easypaisa'")
    add_column("accounts_user", "created_at", "timestamp with time zone", "CURRENT_TIMESTAMP")

    add_column("pins_pin", "amount", "integer", "1000")
    rename_column("pins_pinrequest", "tx_id", "trx_id")
    add_column("pins_pinrequest", "quantity", "integer", "1")

    rename_column("wallets_wallet", "available_pkr", "balance")
    rename_column("wallets_wallet", "reward_income_pkr", "reward_balance")

    rename_column("withdrawals_withdrawal", "amount_pkr", "amount")
    rename_column("withdrawals_withdrawal", "tax_pkr", "tax")
    rename_column("withdrawals_withdrawal", "net_pkr", "net_amount")
    rename_column("withdrawals_withdrawal", "method", "payment_method")
    add_column("withdrawals_withdrawal", "tax_type", "varchar(16)", "'normal'")
    add_column("withdrawals_withdrawal", "date", "date", "CURRENT_DATE")
    add_column("withdrawals_withdrawal", "auto_generated", "boolean", "true")
    if "withdrawals_withdrawal" in existing_tables:
        columns = table_columns("withdrawals_withdrawal")
        if "created_at" in columns and "date" in columns:
            schema_editor.execute(
                'UPDATE "withdrawals_withdrawal" SET "date" = COALESCE("created_at"::date, "date") WHERE "date" IS NULL OR "date" = CURRENT_DATE'
            )

    rename_column("rewards_rewardtier", "label", "reward")
    rename_column("rewards_rewardtier", "reward_amount_pkr", "amount")
    add_column("rewards_rewardtier", "sequence", "integer", not_null=False)
    if "rewards_rewardtier" in existing_tables:
        schema_editor.execute(
            """
            WITH ranked AS (
                SELECT id, ROW_NUMBER() OVER (ORDER BY left_target, right_target, id) AS seq
                FROM rewards_rewardtier
            )
            UPDATE rewards_rewardtier AS tier
            SET sequence = ranked.seq
            FROM ranked
            WHERE tier.id = ranked.id AND tier.sequence IS NULL
            """
        )
        schema_editor.execute(
            'ALTER TABLE "rewards_rewardtier" ALTER COLUMN "sequence" SET NOT NULL'
        )
        schema_editor.execute(
            'CREATE UNIQUE INDEX IF NOT EXISTS "rewards_rewardtier_sequence_uniq" ON "rewards_rewardtier" ("sequence")'
        )

    existing_tables = set(introspection.table_names())
    if "pins_pin" in existing_tables:
        columns = table_columns("pins_pin")
        if "amount" in columns:
            schema_editor.execute('UPDATE "pins_pin" SET "amount" = 1000 WHERE "amount" IS NULL')
    if "pins_pinrequest" in existing_tables:
        columns = table_columns("pins_pinrequest")
        if "quantity" in columns:
            schema_editor.execute('UPDATE "pins_pinrequest" SET "quantity" = 1 WHERE "quantity" IS NULL')


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("pins", "0001_initial"),
        ("wallets", "0001_initial"),
        ("withdrawals", "0001_initial"),
        ("rewards", "0001_initial"),
        ("complaints", "0001_initial"),
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(sync_legacy_schema, migrations.RunPython.noop),
    ]
