# Generated by Django 6.0.1 on 2026-03-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rewardtier",
            name="sequence",
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
